backend:
  name: git-gateway
  
media_folder: site/static/images
public_folder: /images
collections:
  - name: 'blog' #using inroot
    label: '部落格' #UI to see
    folder: 'site/content/blog' #file origin
    create: true
    editor:
      preview: true
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '文章類型', name: 'type', widget: 'string',hint: 'post or featured' }
      - { label: '圖片', name: 'image', widget: 'image' }
      - { label: '標籤', name: 'categories', widget: 'list',hint: '使用逗號隔開' }
      - { label: '內容', name: 'body', widget: 'markdown' }
  - name: 'others' #using inroot
    label: '其他頁面' #UI to see
    files:
      - file: "site/content/about.md"
        label: "關於"
        name: "about"
        fields:
        - { label: '標題', name: 'title', widget: 'string' }
        - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
        - { label: '描述', name: 'description', widget: 'string' }
        - { label: '圖片', name: 'image', widget: 'image', required: false  }
        - { label: '內容', name: 'body', widget: 'markdown' , required: false }
      - file: "site/content/contact.md"
        label: "聯繫"
        name: "contact"
        fields:
        - { label: '標題', name: 'title', widget: 'string' }
        - { label: '描述', name: 'description', widget: 'string' }
        - { label: '圖片', name: 'image', widget: 'image', required: false  }
        - { label: '內容', name: 'body', widget: 'markdown' , required: false }