backend:
  name: git-gateway
local_backend: true

media_folder: site/static/images
public_folder: /images
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey
  
collections:
  - name: 'blog' #using in root
    label: '部落格' #UI to see
    folder: 'site/content/blog' #file origin
    create: true
    editor:
      preview: true
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '文章類型', name: 'type', widget: 'string',hint: '填：post或featured。post：部落格文章，featured：部落格文章的介紹(主題文章)' }
      - { label: '圖片', name: 'image', widget: 'image' }
      - { label: '文章分類', name: 'categories', widget: 'string',hint: '文章的主題分類，如：北屯建案' }
      - { label: '標籤', name: 'tags', widget: 'list',hint: '使用逗號隔開' }
      - { label: '內容', name: 'body', widget: 'markdown' }
  - name: 'others' #using in root
    label: '其他頁面' #UI to see
    files:
      - file: "site/content/about.md"
        label: "關於"
        name: "about"
        fields:
        - { label: '標題', name: 'title', widget: 'string' }
        - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
        - { label: '描述', name: 'description', widget: 'string' }
        - { label: '圖片', name: 'image', widget: 'image', required: false  }
        - { label: '內容', name: 'body', widget: 'markdown' , required: false }
      - file: "site/content/contact.md"
        label: "聯繫"
        name: "contact"
        fields:
        - { label: '標題', name: 'title', widget: 'string' }
        - { label: '描述', name: 'description', widget: 'string' }
        - { label: '圖片', name: 'image', widget: 'image', required: false  }
        - { label: '內容', name: 'body', widget: 'markdown' , required: false }
  # - name: 'home' #using in root
  #   label: '首頁' #UI to see
  #   files:
  #     - file: "site/config.toml"
  #       label: "首頁"
  #       name: "home"
  #       fields:
  #       - { label: 'menu', name: 'title', widget: 'string' }
  #       - { label: '個人資料', name: 'description', widget: 'string' }
  #       - { label: '社群軟體', name: 'image', widget: 'image', required: false  }