backend:
  name: git-gateway
local_backend: true

media_folder: site/static/images
public_folder: /images
  
collections:
  - name: 'featured' #using in root
    label: '特色介紹' #UI to see
    folder: 'site/content/featured' #file origin
    create: true
    editor:
      preview: true
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '文章類型', name: 'type', widget: 'string',default: 'featured',hint: '不要修改' }
      - { label: '圖片', name: 'image', widget: 'image' }
      - { label: '文章分類', name: 'categories', widget: 'list',hint: '文章的主題分類，如：北屯建案, 使用逗號隔開' }
      - { label: '標籤', name: 'tags', widget: 'list',hint: '使用逗號隔開' }
      - { label: '內容', name: 'body', widget: 'markdown' }
  - name: 'post' #using in root
    label: '部落格' #UI to see
    folder: 'site/content/post' #file origin
    create: true
    editor:
      preview: true
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '文章類型', name: 'type', widget: 'string',default: 'post',hint: '不要修改' }
      - { label: '圖片', name: 'image', widget: 'image' }
      - { label: '文章分類', name: 'categories', widget: 'string',hint: '文章的主題分類，如：北屯建案' }
      - { label: '標籤', name: 'tags', widget: 'list',hint: '使用逗號隔開' }
      - { label: '內容', name: 'body', widget: 'markdown' }
  - name: 'about' #using in root
    label: '關於' #UI to see
    files:
      - file: "site/content/about.md"
        label: "關於"
        name: "about"
        fields:
        - { label: '標題', name: 'title', widget: 'string' }
        - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
        - { label: '描述', name: 'description', widget: 'string' }
        - { label: '圖片', name: 'image', widget: 'image', required: false  }
        - { label: '內容', name: 'body', widget: 'markdown' , required: false }
      # - file: "site/content/contact.md"
      #   label: "聯繫"
      #   name: "contact"
      #   fields:
      #   - { label: '標題', name: 'title', widget: 'string' }
      #   - { label: '描述', name: 'description', widget: 'string' }
      #   - { label: '圖片', name: 'image', widget: 'image', required: false  }
      #   - { label: '內容', name: 'body', widget: 'markdown' , required: false }
  # - name: 'home' #using in root
  #   label: '首頁' #UI to see
  #   files:
  #     - file: "site/config.toml"
  #       label: "首頁"
  #       name: "home"
  #       fields:
  #       - { label: 'menu', name: 'title', widget: 'string' }
  #       - { label: '個人資料', name: 'description', widget: 'string' }
  #       - { label: '社群軟體', name: 'image', widget: 'image', required: false  }