backend:
  name: git-gateway
local_backend: true

media_folder: site/static/images
public_folder: /images
  
collections:
  - name: 'featured' #using in root
    label: '特色介紹' #UI to see
    folder: 'site/content/featured' #file origin
    create: true
    editor:
      preview: true
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '文章類型', name: 'type', widget: 'hidden',default: 'featured' }
      - { label: '連結標題', name: 'linkTitle', widget: 'string', hint: '分類用，請輸入此文章在Menu下的分類名稱，如：北屯舊商圈、十一期......。要跟Menu的字一模一樣，千萬別寫錯喔！'}
      - { label: '圖片', name: 'image', widget: 'image' }
      - { label: '文章分類', name: 'categories', widget: 'list',hint: '文章的題材分類(可不只一個)，如：北屯建案。使用逗號隔開' }
      - { label: '標籤', name: 'tags', widget: 'list',hint: '標籤功能，讓搜尋引擎更搜得到網站。使用逗號隔開' }
      - { label: '內容', name: 'body', widget: 'markdown' }
  - name: 'post' #using in root
    label: '部落格' #UI to see
    folder: 'site/content/post' #file origin
    create: true
    editor:
      preview: true
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
      - { label: '描述', name: 'description', widget: 'string' }
      - { label: '文章類型', name: 'type', widget: 'hidden',default: 'post' }
      - { label: '連結標題', name: 'linkTitle', widget: 'string', hint: '分類用，請輸入此文章在Menu下的分類名稱，如：北屯舊商圈、十一期......。要跟Menu的字一模一樣，千萬別寫錯喔！'}
      - { label: '圖片', name: 'image', widget: 'image' }
      - { label: '文章分類', name: 'categories', widget: 'list',hint: '文章的主題分類，如：北屯建案, 使用逗號隔開' }
      - { label: '標籤', name: 'tags', widget: 'list',hint: '使用逗號隔開' }
      - { label: '內容', name: 'body', widget: 'markdown' }
  - name: 'about' #using in root
    label: '關於' #UI to see
    files:
      - file: "site/content/about.md"
        label: "關於"
        name: "about"
        fields:
        - { label: '標題', name: 'title', widget: 'string' }
        - { label: '發布日期', name: 'date', widget: 'datetime', required: false }
        - { label: '描述', name: 'description', widget: 'string' }
        - { label: '圖片', name: 'image', widget: 'image', required: false  }
        - { label: '內容', name: 'body', widget: 'markdown' , required: false }
      # - file: "site/content/contact.md"
      #   label: "聯繫"
      #   name: "contact"
      #   fields:
      #   - { label: '標題', name: 'title', widget: 'string' }
      #   - { label: '描述', name: 'description', widget: 'string' }
      #   - { label: '圖片', name: 'image', widget: 'image', required: false  }
      #   - { label: '內容', name: 'body', widget: 'markdown' , required: false }
  - name: 'config' #path
    label: '設定' #UI
    files:
      - file: "site/config.toml"
        extension: "toml"
        format: "toml"
        label: "設定"
        name: "config"
        fields:
        - { label: '網頁標題', name: 'title', widget: 'string' }
        - { label: 'Google Analytics', name: 'googleAnalytics', widget: 'string' }
        - { label: '個人資訊',
            name: 'params',
            widget: 'object',
            fields: [
              { label: 'mobile',name: 'mobile',widget: 'string'},
              { label: 'author_image',name: 'author_image',widget: 'image'},
              { label: 'bio',name: 'bio',widget: 'string'},
              { label: 'copyright_detail',name: 'copyright_detail',widget: 'string'},
              { label: 'logo',name: 'logo',widget: 'image'},
              { label: 'address',name: 'address',widget: 'string'},
              { label: 'line',name: 'line',widget: 'string'},
              { label: 'lineUrl',name: 'lineUrl',widget: 'string'},
              { label: 'email',name: 'email',widget: 'string'},
              { label: 'description',name: 'description',widget: 'text'}
            ]
          }
        - { label: 'Menu',
            name: 'menu',
            widget: 'object',
            fields: [{
              - label: 'main',name: 'main',widget: 'list',
                fields: [
                  { label: '名稱', name: 'name', widget: 'string' },
                  { label: '連結(內部)', name: 'url', widget: 'string' , required: false},
                  { label: '順序', name: 'weight', widget: 'number', required: false,hint: '數字越小越優先' },
                  { label: '是否有子項目', name: 'hasChildren', widget: 'boolean', required: false ,hint: '只有主項目可以選這個(其有子項目時必填)'},
                  { label: '子項目的父層名稱', name: 'parent', widget: 'string', required: false,hint: '只有子項目可以選這個(子項目必填)' }
                ]
            }]
          }